source 'http://rubygems.org' do
  # gem 'tty-prompt'
  gem 'tty-prompt', '~> 0.10.0'
  # gem 'activesupport', '~> 5.0'
  gem 'activesupport', '~> 4.2', '>= 4.2.7'
  gem 'whirly'
  gem 'paint'
  gem 'artii', '~> 2.1', '>= 2.1.1'
  # gem 'curses', '~> 1.2', '>= 1.2.4'
  gem 'colorize', '~> 0.8.1'
  gem 'tty-cursor'
  gem 'tty-table'
  # gem 'faker'
  # gem 'i18n'
end
